keys:
  - &server_MGC-DRW-BKS01 age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
  - &server_MGC-DRW-BST01 age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
  - &server_MGC-DRW-DGW01 age1a9vwxjsy220jjeauf2kll6fn3mvltzx9rujvr75ea7w696v4qqvsu376j2
  - &server_MGC-DRW-DMC01 age1atakc2r5uxz97r64lap73muc7gdydvqfpczz8dlwh85pqrr7gpss8kr9j8
  - &server_MGC-DRW-HVS01 age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
  - &server_MGC-DRW-NBX01 age107607wh3eaq4n9pxjgtvpfy0puf9eul8a4lmtt0u4cnc4t2h749qz29tcw
  - &server_MGC-DRW-SEM01 age1mkzcyetggc8ftex6awe3pyjy82nw5t390qdzjy5edumplz2v7clscky7r0
  - &server_MGC-DRW-VLT01 age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
  - &workstation_MGC-LT01 age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg

creation_rules:
  - path_regex: sops/default.yaml
    key_groups:
    - age:
      - *server_MGC-DRW-BKS01
      - *server_MGC-DRW-BST01
      - *server_MGC-DRW-DGW01
      - *server_MGC-DRW-DMC01
      - *server_MGC-DRW-HVS01
      - *server_MGC-DRW-NBX01
      - *server_MGC-DRW-SEM01
      - *server_MGC-DRW-VLT01
      - *workstation_MGC-LT01
