semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:yAjQzf7IlJ0I80CTBdKaplM6jNaDThUaxMWhAA==,iv:y3oRRhPHtibrtq5NpNQIawAqHs6CacxEtq5yHry4Cy0=,tag:3vrpuaMaoGSBFKaWeLHyeg==,type:str]
bookstack-keyfile: ENC[AES256_GCM,data:BkK7jrmgIy7OUmrErrhqLHecJk13gTMTuzNvwNXcjJaQxzDbz0Stz6LRc6mCgzIgiWbz,iv:AMuco6K5/v9hP6yzWFS43GtMx3giGod7sQ/LF1bgdSs=,tag:239EuedaBBP0we96TWW64w==,type:str]
sops:
    age:
        - recipient: age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM3hRYTJDSVVZNlp6ZUJs
            MllRZld4djZrNVZPTjRKMWtsTGZmTDBDeVJzCjFBSSs2TXpQVUpXNE5VOTFCak8w
            R1B0ZXBob3pRaFh2Tlo0cjhudmlKMmMKLS0tIHJCOXdiV2E5VEJoQTV5ZWc3Tm5X
            ajJTQ0xvb0xyeTlaU1ZVVjhkUm5nQTAKJE78r9Zs9Rx3fWvMsjd/4LzgiaXgTlWQ
            kzMhW0wqFo3XHhIE5bO+jFaUocMaSg7yQIYbiSRowMLbrj5w5uQN8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdVNWK20ybnp1MDVIVmcz
            dklHNlJteVN5WlhTTkRuMndOOXdJVDcxV3djCkVRVjk2N2ZFU0s2R1JnMnI2RlVC
            bFVyQjFqN1lwU0ZjclRBL3hDeXVFZlUKLS0tIFR4eFFIS3BuYXpLa0M5c2RxaXBw
            YjR6ODZBcVNCK05LdmNKUWVjdTllMUUKuRRzmD5qujA6TbI0tHCk5JfARHGLoyRn
            OLuhMms6jEBtaW2xWZUcOoehpK4AR302gP3+2RDWeqZOXGvr9bO08g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ycsdrpwydpw89ae5tpmmwzwplgs2ne20k9ypyvknpz6faya7evquq4nmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR2pCTjJFaGdCZTdIZ01t
            SFg5Vkh2bXh1YzAzcjlPQXRmcmZjMW9yN3hvCmI4Mkp4VWlYK2UwbTB3d3ZhUDg3
            aEU5a2xtOXVmc3N2eHRFcERZUjN2SlEKLS0tIGEraWVqdzVJMUVRZUJNazdjMldr
            NUZoRmZheXNKQTR1ZXJNNEVYaU04RVUKlrW/rkln3MBkgrByX6TCWJOQPg+l6t30
            zsLauD79j/dZQ65k/u528++n8H1sK51T0YEr4wrIKD3heWUxIDrhIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtckVDZ0N5R253disvNWIx
            c1VPei9VQnlCL3I5VTZFMm9MWE9KMGcwMm5RCjBIK2VEUkdzckV6Z0Q5NXpOcDNX
            WVJYM0hvTnQyYXF5VW1QaUJLUExrNjQKLS0tIE9RMjNZY0xab01nYTUyamphcE9u
            SVYzemFWUHhVeFNsWElhTHV3M1RxaGMKs7L46Gx7+egedtfMmCpTfgc6OTFw/7cR
            284Ln1k59d4hHDE80ZILur+IgLF8IA3NKTEDDcZAaYkVffQN4oybEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkzcyetggc8ftex6awe3pyjy82nw5t390qdzjy5edumplz2v7clscky7r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ3d4T1lmdFJTK0xTUmFJ
            MFJOS3BreDJCVkFOVEdWUFlSUDRNa2VTU1VzCkRNUjF3NEFjL1hERThJRTRCRCt6
            L2NjUUlmYzcyTVliV2oyaVNlK1ZVMUEKLS0tIHpZQ3VaYnovbGhxc1ZWanMvUzYr
            eWtvMDV3dHBZWVk5TjlWUkt3N0lXUkUKwEEz11evjKfjtC6ksYmp06JVNq4n47Ue
            5EnwwueQjdBFiJrE0R2C+kzQ0qkZORWcdf01RlD3GkyeKhNepu8GvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMXpHL1k3d2NuTlJIU0E1
            d2E5bjNkbHQrTTNBa0d2QW1RWHRLMjdFQkMwClpqekR3RWo4TDhnK1lsVFpWNzZB
            amZmL3lSVGtJd0ZaME9iaU1rc0hmdjQKLS0tIGJtV2svQ3FmV1V6UUZoelZuUm94
            SlIzaTVuU3FVNE1WWnpGbnVjRmN4QmcK63ua82/0PzJC2qA4nNR1k1CEugnWs/7P
            4HIxCl4maliTf/kCdExDsqFJCpo1xFEHxz74ShC7eeNNtD2ZFxIXBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeU43VlpNbnBJbExkOSt1
            Y3Z3ZVZiU09wOHJjTFY0S3I1MWRtM2xWcVNRCkVMY0ZWblBkb1Y2ZmROSVNJZlE0
            L0pFTkJ1WWk3N2xSQmV4VHl1UkVNTFkKLS0tIHMwOTM4T1FXbmpkNVk1UEhzOWEr
            djZQd2hiR0JOM0dzUWdldEEzQXNLa3MKIp6BlS2M8wFS/qehhYh0aGRaJWZjJ3wO
            8DsoVGJdcW4XKTTDHujDk/3eqQwAXCr4XA3zIff6dC8VWgN48RfUDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T06:34:19Z"
    mac: ENC[AES256_GCM,data:tIOYEeZB3HpnyQsVKWDd7/cSViCDBalwH8Lxg6hzluHN80EoSbJTfTAjCM51n/dJrdDbJTTsEu2IahXuJzDfquQq6of3Cu4CI6ltQFsopcbGnzgmOVrHJAN7ul1gCFv4l+oezSvDQTLabt2Mqz71sJRnrEw8gF4s4MR9RcZtsC4=,iv:aZNuo1SIcY+ykvjFOvlprWBMZAhjrUq1WzxXHKOHkM8=,tag:rSRBcf09WgyLRtG2myX1iA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
