semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:yAjQzf7IlJ0I80CTBdKaplM6jNaDThUaxMWhAA==,iv:y3oRRhPHtibrtq5NpNQIawAqHs6CacxEtq5yHry4Cy0=,tag:3vrpuaMaoGSBFKaWeLHyeg==,type:str]
bookstack-keyfile: ENC[AES256_GCM,data:BkK7jrmgIy7OUmrErrhqLHecJk13gTMTuzNvwNXcjJaQxzDbz0Stz6LRc6mCgzIgiWbz,iv:AMuco6K5/v9hP6yzWFS43GtMx3giGod7sQ/LF1bgdSs=,tag:239EuedaBBP0we96TWW64w==,type:str]
netbox-key-file: ENC[AES256_GCM,data:vSR05kPuaf788PTHxiTnwP4BQSPxKpunBh7wbaVie93ehxVFdOmpGCGRE1nf3A5Tj44Xxmqx2dkAybgu4ky2nbEmbrdmTC6tqdntAxsiKoJYlKJ5jBfcfiOSEXRt0SDCBf8Ejw==,iv:4qKKwhaslH3216WX/68mM/UefLVRXAvpiH1Jj1TlGSU=,tag:t8e5qigrTxRbDMLihvFcpg==,type:str]
lldap-admin-password: ENC[AES256_GCM,data:cCZMB/cfs6w=,iv:00I2Zg0VdNYLdWBLiOoEXMCxM11Bwxjt4yAXbcz5Mtw=,tag:epniOlHTegGTGFt6GQcR5g==,type:str]
snipe-keyfile: ENC[AES256_GCM,data:9lnP4J6fN4LBSqAHszUd2UJSJvqXbSboPvU/I+usMd65ma7n4+VmJCjisgI=,iv:f1sk5fZCyQN3TgVxhc06fO7G65Q4EFMOkJcjvrtsW6Q=,tag:XxWxFdMikxquHqVTRgtwFA==,type:str]
neo4j-auth: ENC[AES256_GCM,data:uTRkO5njVfmQ2w8FcHqEqcHZjpR3uCcnoDHqMG0TMng0aXM=,iv:7SP0id+8ylPP6Xf91QPHLsjHdRqZId+VNQe0oEK5jvU=,tag:E2hGoZXYFiEzcOQQWwM67Q==,type:str]
bhe-neo4j-connection: ENC[AES256_GCM,data:Vd8S0f/C0DnmEeSQaT6Jjb8WN3d3ClDwcvt/Zzpj60ZXz2eG9Yic2KftRdlo/HteY61BZayR4UUnP6V7Pjht0OM=,iv:Drzz69UeOAhLweJs9ilUJu+x//Z3FgOQtYDlPMc1PR0=,tag:ZTTHVrKGLxu25nhasam6/w==,type:str]
bhe-database-secret: ENC[AES256_GCM,data:AG1YIj84/K/nuvle/s6YJhlfaCrIagQ6Pj+5bQgYNjCzBAvuvAURAA==,iv:QV7+w3HC8PU0v0tOcVbqW62WgLOh70KbvMt5OVdO8y8=,tag:jTYSBEjMlmDkUV1+2PbxJg==,type:str]
kube-token: ENC[AES256_GCM,data:dWbd3z6Ugm7Mf505xNLSXgvn73wPdxyU+Tzt1qcnMu5vCmogT2/jUU+19ZYcCYEuWk6zO1ZYyC8p31UevXFiKIAgtEQQ6QFYvC5hNpnZLJy6apPBFuTshpTLN6dhx/Hg1+SpO/x6bd8Gs7qM,iv:gbSo/i5ykcwZ0IS+3zY9Un6VjTRxylzKvoYZKg2sSBk=,tag:h7gSpcCs4smoZJlN6Eu9Gw==,type:str]
sops:
    age:
        - recipient: age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadS8xMVpBa1hLUGJaUEtt
            aXdTYXZQalh5MVVKcmVsaDAwVTgvNHplMlQ4CjczT3cyanhnMjFVekVJWTluMkJi
            Nm5IV0dLMmtYdGlLRnFJQjlQVVkwcHcKLS0tIE9PbUxrY1RFWkdQTnhkc0xRZjRv
            b05xa0JtRzBCMlJLY0tkeFJSQjhUY1EKARb55/7oSa9pEwbc+6ebRL+GsnzX3NWd
            TTIT5nIzvxG8XnVSLucTBJqExM66TGiwnkHdo79XRStc76qR34NduA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTnhnbEk0dTJKeWlodXVj
            bzNOVUhlUTcvWFRMYnlqVk5ENlRVaW5nN0FVClhURXhxZmJ4T1B0aGpMOHhjK1Rv
            cVhVd1JsZ0RIbEZBNVIyMy83SWZzVTQKLS0tIFBLUTduSjNGY0lrMmdrRUhvUUpX
            TmRqeFI2ZUw2citoWXR5Ryt5SnN3b0EKqxJWKWPwpBnLaNu2CMVU+aVj85rGgwo4
            InYs9GnlMPEVsi3QRbzrDkGu/D44AQLhSLXXgugIlq2/Jnrw1xiVog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9vwxjsy220jjeauf2kll6fn3mvltzx9rujvr75ea7w696v4qqvsu376j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TVJGZHlKSkcxVkxVTTRH
            Si9Wek9UZncyVVMxNmRSMXBSVWk0eGUzOWs0CmVFa0dKOXB0cWFLcy9lSkdFTExW
            MUdSaXlpMWpaMmRmS0pNa2I0Z3hoQ2sKLS0tIFAzcEdleEh6SHgya096VGgyUmpV
            OGVzOHNVMU15Q1NzdG1PRlJpZVRUK3MKgW6/2xmXG5ef6bkKQ/vaHXBop+4F4bPA
            EN+xArpfbU+/oiZi76ufIbxVJ8OwJy08lOWZ5IbafjSpGShHnpQY9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1atakc2r5uxz97r64lap73muc7gdydvqfpczz8dlwh85pqrr7gpss8kr9j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUFAySlJxWktoNTA1b2k0
            di9tUlVXeUt1b3p5MndHNzBWTFVNL2lKQkhRCkxpSEZjUVNWQVh5Vk5wd2dmSld5
            dzRZdS9WMHNkb01VaDZnRnQ3Z2laaGsKLS0tIERMK1FIV3hNWnVoaEsveDdwUVNs
            VTVwYVUwMWY2SkxpdXIrc050b3JyMDAKTZR4blTHwuyaApjP1K2hHgU9oJNxMP8O
            1rfM0PEc5v/x+yeH6cbH7nh+aFG65OX7j6yhCjnFqPYC4YW11nKCnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14cymtuyupa8xt46xy8e35l0qznq6v7wvjzxzha95hmplxcvc8yesu06jr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZDl1WTZIK2pHTUFGWDlj
            YldhVFlaSXFtMUVob0NjRW9Sam1tM00wZlJrCmtQdXozbmJuL2pPV3lESUV1ZDhD
            aVVBMkEzbzdjLzZ2bjNhSnp6N0E2emMKLS0tIExtU3hCTFpUUm9hMW9BeVIwKytE
            UXVPNzVWVWZYczFkZ1ljeHpzMXE3VkEKNLzvaS7zWAEumjzbHpcAON1PALtbRqHt
            vhCtsQammOAGMt8GaLEW1V/Jy/lrFlrsH87ANSYBUnxfpWTLUdQxhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdTBKQmpnaEpiaHVLQ2lN
            VHVYRGdjcFJKTDdWa0IwSms5SFFseThDanpJCnBTRW95aTJnckp6YXRYKzNBZDdv
            YmRZNk1LVno5czYzZEZGckllb2xpUG8KLS0tIDJpSFJpTS8xTXlXcC9NZlUzZjBU
            eTd4SHJFTjJiUWVicFIzd1BOeThPeXMKs+xAzEGS/1+Vx6GcBUtgTPgsb/xiNiEc
            Sp0eOHl2epzb+M7gy3WC1fsYcG+27BrQdAVlzQiVvV8JZzsrcgHMhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age107607wh3eaq4n9pxjgtvpfy0puf9eul8a4lmtt0u4cnc4t2h749qz29tcw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVEFWdFdncDdhRU1BUFBm
            VWdTaWZON3NBS0ZDeFhhY3RFNmNDQ2IyOHpNCkpHVW9PTWNNa1A2N1JiV0JDcHFw
            Z2l1ZzN3NThCWnJSRzlZZnZWK055MkEKLS0tIHNQSXBlb2pBOUU5V2paVk5Yd3VN
            REtvOGUzeHhnMkFjL2lGbmpBVzhVdVkK3YtK64lt68/Eve8pxkPGeb8UeGFY07X6
            C35/otqHe7HdQzQCiCdYOj//YuGfpUG5BSikVVl0xpy2NMLKVv1Hkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkzcyetggc8ftex6awe3pyjy82nw5t390qdzjy5edumplz2v7clscky7r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dFdQVVhnbCtWTm5MZHdZ
            SlVidVZQL1lRWENCUlAyRzhvUEQ2WlM5NVhBCkpJa3hrT1ZjYW0yWUxiOWhKS2NZ
            Z0N3NmhaK3paQ2h2MHFmeGtiMHZJWmcKLS0tIHkvUEVGckNUaFhvNVZoRVRvWXhN
            TDFSK3BYL2o0eFNCMncyNmpsUzY1YUEK4ceCHkxNg9weYYmazEPtmNzT56Mg6RiR
            onWJ0+3Q8vNgjrUsRBOY7Y114ppG1vcxpFpg3JHNGv3SkJlPcSPhxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0K1hGbTNkVzlFNWUwUXBv
            amN0cCtwd3E5YjA2SEhzcjRtMXk3V3kwUUFzCk83Q0o1SFN4ZjNoRkNYV1RLeDZi
            L1R2M05TS1MrL0hVT2V0YmVoZE9MWkEKLS0tIDJNenBiaVJKcW9QaGcvR0RSdGYy
            cDlQUzFuOE5qTlJ2eXdKbTBoWERnQ3cKWiVSEuBAvzcG05cALuTp+J4WpK/CTphH
            r+7X0wTyJQ7f/PWvD5NxQj/eH4Xo322/GWiHT2xRsWcdV9pX9bHOBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZHR0SFUxaFN1c0cwL2oz
            dEV3MGwvVXE4Q252RFR6aWhzT0t2WjVNZ0hVCk9tZjhzZmJhbjFLVG1XQVM3R01B
            QTJ6eHlpb2ZHTGE1SVJlWUhxRkVkQ28KLS0tIGFYNmhEcEpFQXVPVTFRZml6WHZQ
            Z1BDcjRGdDcyalpzY2NlbTUrQzAvSjAK6EyEklH9vqMGbPdCjgtr7JlGaelmwTcy
            sRelHw3AUHGtCC5TwZWUYEO+xq+TvQERKTLEqE14fRjjqWbGi7HqEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T04:31:57Z"
    mac: ENC[AES256_GCM,data:21/i1SxbbDdoh5t/ju54fVEPshqOCp/q1eBHF+BVxGf2PKKRc9J4JN1dINB9SoDBA0ZRgk3bL2FR3VqHH0e67MmlVQ2uTNzKImXGAFY5+xxcYJY1IBswdnxHOdtCd7jAEQHaMFUfZJ5o04Eg5U1NdJR+sFZ6urEDcIFxi8AO+Q8=,iv:wQvmX7AIfn83g1urXg8+KSdOUL/pHqiPLEXYiyFcQTc=,tag:r328d7LS57OQkXM0TQv56g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
