semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:yAjQzf7IlJ0I80CTBdKaplM6jNaDThUaxMWhAA==,iv:y3oRRhPHtibrtq5NpNQIawAqHs6CacxEtq5yHry4Cy0=,tag:3vrpuaMaoGSBFKaWeLHyeg==,type:str]
bookstack-keyfile: ENC[AES256_GCM,data:BkK7jrmgIy7OUmrErrhqLHecJk13gTMTuzNvwNXcjJaQxzDbz0Stz6LRc6mCgzIgiWbz,iv:AMuco6K5/v9hP6yzWFS43GtMx3giGod7sQ/LF1bgdSs=,tag:239EuedaBBP0we96TWW64w==,type:str]
netbox-key-file: ENC[AES256_GCM,data:vSR05kPuaf788PTHxiTnwP4BQSPxKpunBh7wbaVie93ehxVFdOmpGCGRE1nf3A5Tj44Xxmqx2dkAybgu4ky2nbEmbrdmTC6tqdntAxsiKoJYlKJ5jBfcfiOSEXRt0SDCBf8Ejw==,iv:4qKKwhaslH3216WX/68mM/UefLVRXAvpiH1Jj1TlGSU=,tag:t8e5qigrTxRbDMLihvFcpg==,type:str]
lldap-admin-password: ENC[AES256_GCM,data:cCZMB/cfs6w=,iv:00I2Zg0VdNYLdWBLiOoEXMCxM11Bwxjt4yAXbcz5Mtw=,tag:epniOlHTegGTGFt6GQcR5g==,type:str]
snipe-keyfile: ENC[AES256_GCM,data:9lnP4J6fN4LBSqAHszUd2UJSJvqXbSboPvU/I+usMd65ma7n4+VmJCjisgI=,iv:f1sk5fZCyQN3TgVxhc06fO7G65Q4EFMOkJcjvrtsW6Q=,tag:XxWxFdMikxquHqVTRgtwFA==,type:str]
neo4j-auth: ENC[AES256_GCM,data:uTRkO5njVfmQ2w8FcHqEqcHZjpR3uCcnoDHqMG0TMng0aXM=,iv:7SP0id+8ylPP6Xf91QPHLsjHdRqZId+VNQe0oEK5jvU=,tag:E2hGoZXYFiEzcOQQWwM67Q==,type:str]
bhe-neo4j-connection: ENC[AES256_GCM,data:Vd8S0f/C0DnmEeSQaT6Jjb8WN3d3ClDwcvt/Zzpj60ZXz2eG9Yic2KftRdlo/HteY61BZayR4UUnP6V7Pjht0OM=,iv:Drzz69UeOAhLweJs9ilUJu+x//Z3FgOQtYDlPMc1PR0=,tag:ZTTHVrKGLxu25nhasam6/w==,type:str]
bhe-database-secret: ENC[AES256_GCM,data:AG1YIj84/K/nuvle/s6YJhlfaCrIagQ6Pj+5bQgYNjCzBAvuvAURAA==,iv:QV7+w3HC8PU0v0tOcVbqW62WgLOh70KbvMt5OVdO8y8=,tag:jTYSBEjMlmDkUV1+2PbxJg==,type:str]
kube-token: ENC[AES256_GCM,data:dWbd3z6Ugm7Mf505xNLSXgvn73wPdxyU+Tzt1qcnMu5vCmogT2/jUU+19ZYcCYEuWk6zO1ZYyC8p31UevXFiKIAgtEQQ6QFYvC5hNpnZLJy6apPBFuTshpTLN6dhx/Hg1+SpO/x6bd8Gs7qM,iv:gbSo/i5ykcwZ0IS+3zY9Un6VjTRxylzKvoYZKg2sSBk=,tag:h7gSpcCs4smoZJlN6Eu9Gw==,type:str]
sops:
    age:
        - recipient: age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcld1VC9xbks3Z2NMN09s
            V0QvTzIrVWNXSTcvVmd2a24rY3hya3JBR3dRClBxcG1YSENBVWRCRVNYbWdud2Yr
            MXN4QnhpTHdUdHpMbkdOWG9rcnRPS3MKLS0tIFpONVdjbmhTNXRmLzBrNnMxRkcv
            ZklLSnI5YnRmVURUbE9iWWcrUVZNUlEKRQ40t2RbuGF/i9nQqBcga0jNpxfRQ17T
            lExq+CWde90X2Jg8qnAT5aM8ow0asB1A9aRrQeHcTIZt7xmwxYw97g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQmxUckUwTStuS3hkVkU1
            RTJRa0RyNTNrWFZ0eTYzNWQ5M3RkL2pZNkI4ClhkQVgyN2gyVk5FZmQzVHhFb0cr
            Q0RTS04vVkxuTkUvQW1lUVArVzNaWTgKLS0tIHJyYklLY3Z6ZGczTmxlQkdjYmlV
            OWh1TDk5cllpYXE4cXcvZGdaQzMwVG8KuUi/O4x7/21+TxLfIXXfjQ7CjVZ/v8JR
            ntdaJ10mrjGqHEflp6+NQg3SkzDJJxJh/YlhG5IQ5lHlR9uBP38cMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9vwxjsy220jjeauf2kll6fn3mvltzx9rujvr75ea7w696v4qqvsu376j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SmVlaTR1ais5MFpOMlRG
            UEJ4c2dzandHbVc4VkZpYjdsUHEwTU5SUkJZCi9iekJjV0ZJZ0dBaGQyVVp1YTFS
            ck5JVUN3cytnSGlncEpScVRKTW5oSG8KLS0tIEJoZWs2WkNmZnp3c1hXa1BacXB4
            THp4eHo2OVhMODkvK3F5c3I3Tkw2YVkKgb9CmLCKJK2Tc6s3MwDDj0OmOOiM0pIu
            8WNcTf4dOXBTdUVTwI2EuEHNl/3/CxWVDjq4pU4+N0nnBAxYX/fARw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1atakc2r5uxz97r64lap73muc7gdydvqfpczz8dlwh85pqrr7gpss8kr9j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS3NXWmhsSjZYcHlpKzlI
            Yk1tdmJOZWUwdm04Tk4zeHh2bGNjSSthTlNvCmJSSlFNWUs1emc1R29CeFZHOEZt
            MDVQUG1RcjQvbWNnQVFXUU9yQWhaWnMKLS0tIGdTVkpOT3NyVWVRRnJESm00WXhm
            TVJqMmE2RldjdGprY05HVjhEUUJwbjQKbp8qxivKclIQ6VzpldMwvdmGGwEz1t0T
            6xYYE5H6E/p9yg/HMK+uHwlDaspCMkGWji67WPcAwW2QINYaD6vkVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14cymtuyupa8xt46xy8e35l0qznq6v7wvjzxzha95hmplxcvc8yesu06jr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV2M3TnBpc1BXT05KNU9y
            bWtyYVQ0aks1OEMvanA2dlNva2dtU0NSUEgwCkNlWkdnT2hJZDRjT21UTkVLcnFq
            N09MMVZxSHdkT1Z0K0VNUU5kaW00S0EKLS0tIDVwTFRpWmEvbEp0Z3l3eFROdmhk
            U0pTNmdsSkxaY29aMHkrMG5XZlYrVk0K1mAohlXRv5ZAlMp+Joa5DnBp1AgU82pm
            VcB8V91LlzhuYc7+Q1oxqVP+rDUlcy+kaNv90Y3VcesOmnkrAxiSyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkx8zl440ur3ju60cgsulvuwnzkqd9wfjjh928dn0c0tkuksppdqmlzgna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBha0hMOCtuUmM3Ym5zdmp4
            cVRUQ2hyVnB0d1Q4RDRCRFY3d1B2ZzZZRlhzCjl0cHYyRE5RR1RXZmdmMXQ4OVRm
            RzRBcFRaazA2SS93N3NMclVBbHE3Tk0KLS0tIG9mZFdKdGg1VUhURVcwYVVDVTRS
            RFA5VUxnNk16YllyWEhaRENwdG9GejQKu9XfRYiDxwWxbr0610q7IFWW3Z5hcsR1
            SIz75etuiOuC34TUIGugUHHsSK2Jz5p2g8LPYbse2x2R94O80s5RKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYkpRS2R1VVRCSEwwM3Jx
            eWtLL1dNZW1NaHptYURBbHZFb3VOSXlLSWpzCmdtZWhNTW5SejZHSVd2T050bWhx
            Wm85SWhEek82NmNJeW5pT3Zua243dGsKLS0tIGlnVnkveVQ1Wi90OWg1Qmc0TzNL
            NkhPWmJraW82RFZyNEFhNHk4eGtYa1EKOWZLoGYU8/IzqmasuOkP0IDd+Q7zE97R
            8ZD+pmtNqdY8FZfygZjF3l4CH9YEjC8e32vuYm6kpOyhe+sjYBqcdg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age107607wh3eaq4n9pxjgtvpfy0puf9eul8a4lmtt0u4cnc4t2h749qz29tcw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUUJpVFhxYmFCcjhlUmxk
            L2pFM0tyTXQ3bTk0WXVpSmJwa3BKQ1FiWkhBCjZmbVQ3VWpOK3F6NURsbmFQNFUz
            OG9PczEwWUJiUkhqMzZUdG1pTHFYUzQKLS0tIHY1NU93ZGwwYThObFRKTUVEZlE2
            Rmt4THc3aFhkUlQzdXpvZm5DOFVKSk0KswlYU6oA87cViSVQ9pQVQgJ2GB16+eVd
            /b5EpY7DCKQTJTK77k7CuYCFwq+rFP6hSLo8kzSlJMAoPkqTBwWH8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkzcyetggc8ftex6awe3pyjy82nw5t390qdzjy5edumplz2v7clscky7r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNUNLZGx1Y21GM0VybjI3
            RC9kZUdOdDh4NTNOY2YxVWVXY0xWUno5T2hnClptWnpmVldWbXFZSG94SldORnlP
            UTl0aUNjYUE1ZFZKWk40Z1p2eEJmaEkKLS0tIEhKVGlkaTdLdi9ZWENBMC8zZG93
            UDk1RTRpNlpGTTc4U2Y5aDlWUy83UzAKmbRmdktBohdjgFAtztOhSWdnfHB+gegc
            8VnykRWlASIGQ0SWQDfdJJAuAwFBTU4meCXP2MCqQPY53LAX6y4gGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZVJDSXJxSWEzSVpsaVRE
            YU0wblkxbWlSQTRKRFdtNDZGYUdxK1hzcnprCkx0ODJCWnI1cGlBbkxRYlYvNUpQ
            clhiQm81ZE0wUE8rRjR5SFBycitDeFUKLS0tIFNDU2hVUU1HTTdZT0pjcUVvTENT
            ZjVzcnZQWklHbW4vZmpXQ1NZdVA1ZUUKkWFjZTU9juv6X5F/fCIoDjTrqEH6K3WT
            X/mtMrmPxu2/k6EPii6TtzDfNwNQ5jKQxPWt2u4jaRmQLMZxNA4wDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VDNrY3lvS0N0T3JobWhO
            QWFENHF2QWxBVDllZ0RMb2ZMZ3NmTStwZGdZCk5sOTBNTHRoTkVscTF5ZkNGTDF2
            OVorNDBHdmlOTTdla3Nwek54ZG14RFUKLS0tIGZpdUdCekVJdmo2Q1VvU0RaYXpE
            OGgvbWt4clNiZFMxNjhybFpEUVpWVkUKTsVkQirkfmVjO2H/QXoGKHNlQk1pMXq5
            jLOlvzh8gcM7fG06K7XNie09yXQsnM1gKUju4v5SuMGvn6ITYH/Awg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T04:31:57Z"
    mac: ENC[AES256_GCM,data:21/i1SxbbDdoh5t/ju54fVEPshqOCp/q1eBHF+BVxGf2PKKRc9J4JN1dINB9SoDBA0ZRgk3bL2FR3VqHH0e67MmlVQ2uTNzKImXGAFY5+xxcYJY1IBswdnxHOdtCd7jAEQHaMFUfZJ5o04Eg5U1NdJR+sFZ6urEDcIFxi8AO+Q8=,iv:wQvmX7AIfn83g1urXg8+KSdOUL/pHqiPLEXYiyFcQTc=,tag:r328d7LS57OQkXM0TQv56g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
