semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:yAjQzf7IlJ0I80CTBdKaplM6jNaDThUaxMWhAA==,iv:y3oRRhPHtibrtq5NpNQIawAqHs6CacxEtq5yHry4Cy0=,tag:3vrpuaMaoGSBFKaWeLHyeg==,type:str]
bookstack-keyfile: ENC[AES256_GCM,data:BkK7jrmgIy7OUmrErrhqLHecJk13gTMTuzNvwNXcjJaQxzDbz0Stz6LRc6mCgzIgiWbz,iv:AMuco6K5/v9hP6yzWFS43GtMx3giGod7sQ/LF1bgdSs=,tag:239EuedaBBP0we96TWW64w==,type:str]
sops:
    age:
        - recipient: age13ycsdrpwydpw89ae5tpmmwzwplgs2ne20k9ypyvknpz6faya7evquq4nmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNkJqRDUvV2dBWVc4d2NO
            Y2w0UEgrdmozSGdINFNOVHREYmE4NzcwVVF3CkRwYWlORDdNbngrcWRTWU1lcThG
            ekJrb24xZnVVRDV2NmpFWXM5cHdFdzQKLS0tIHZIQmtWTThVTkxxdFpOdVIyOWw0
            ZE5kM3VaMnRWQVNsazRsaUl1bWtmeUUKGsgZKHySJiBHJNVALnyeq1EiGDVS4LDJ
            hgg8dScQa9v7tXcVj2QZmcifLR2nnPQC+VJ0BM6i4Ctz4kVT6hMcnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5V0tNKzFnOExCSWMvMVg1
            aFZLY2R2WnRRR1VudG9sQ2NBcnFXREhJeUNBCmpzV3BrZ1hiVG1zc1VqY05FRi9y
            NGRxSU93TTRFVmYrWVl4NEFDQnFqRlkKLS0tIFR2QWgxcysxWmJaS0xnNkJvbWoy
            STgwTjRIOFhzelJuRzc5Ync3RHpDUDQK0nL5CuU6htxhOKdQv4BxvyU2DpKW0Mzg
            n5WetddIfofE2hZPY4KrZHVNkukvVoc5VuM9JuV+dy5TQ5pv6Iolfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNE1tcTIybzdvSXArVG9n
            RlVKZGZiNkh6aHNLUUdtUGhyNDdXM2VpS0VJCldxZTM3cXh1SWZjOG5TenZ0Vlla
            UEk2UEwycFZQWnhyMlNYNTBDeFBZZGMKLS0tIFBJTEgxUkVkTmU3R1ZQNG5WeUtt
            REpFZnVsNXB0Y05YaE1weGdlclhGd1kKP4jkbrqAMviwt0mCqMtNSEYchKmomS2Z
            WFUXkPmNodtivePc9EvFY+4qzRRYChux5kFz+7pxNNLktZM+v37+8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSkxxZ2hXd0pmVERsbmhn
            NXUyWTNOZ3k1dElsOG5EZy9LYThadXgvcmdJCmdHZDVPTXBHQThNc3JGdWFzbkxP
            RCtJNElkeEo2UnR6VFRsK21UYjBzV0kKLS0tIGZqZlNEdHlGcEtYdTBoN1RBUFhk
            MFBpRVU0RkRZU1hUL0RNdWM5SkxZTWsKzHQQLvRhxOWOpVb+pdmA8o7KcYcKqV6x
            lVo7Ww+uic7+9e9h01qRe09scnTD4fSCA7vP0t/nbHNj9IYgESan0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByODhmZEJQaWk3Rmw1ZUVB
            eHB1MlcyNC92R0FONWNQV0t0citvNVRNTzNjClRzMWh0RldyeU9FTVhyRkdXcDgz
            YmRyc29WbkpEanFUV2xhVU1kTHVGODQKLS0tIDRteVM1SGg3QmVEbTVvTm0vWlRk
            WDc1cGllSmZoRkFJbTA3MWZSc3FzaWcKWHlwTzcrMo813YT9Pr3NKz6uOVYJ0wRx
            E1zllG/Ku26sGBil8fFmqOfnhd3L3dzKpqHBkiudEhhj9WeIucIJfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL0ZwVmRmUVRFZjRsL1E4
            K0VrSkJBU1lvMy9VWktTSUgzalZuS1NSOG5vClBRejZGR2hEeFdWQnd0WTRndzc4
            YTZqc1QvZklTbzgxd0lXVnRDRjV6VjQKLS0tIHlEZi9GYVpUOHdIVkFObUdjeHBj
            djFNWXJpeTluM2dxTTZKZnVBV3V5TnMKjgRgOsuHlGIhEWUDXqpLlbx3PjHn1Y/u
            K9tixx2oEyQk2sLOXDyKl4u9ixutF8JORf7Y6Vqu+LkfQi6Pd3dfoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T00:04:49Z"
    mac: ENC[AES256_GCM,data:tXSxQp9PBvNp0xVc6EAnFuIhKDVTtPXP9ShIcDBQ0DQjec2Txd7aqDi7AmqIWg4NW9AMMrCt8nCq3Z5APyrTWfzIq1x3FJ5DXhWHMlHs+Jdx1YRVqL+ixEvl8gM0p3JeL5Hgr01FXI0KvFo6riJAy9qL1ckV99+j2zkuzFYeUOA=,iv:zM2QDL/w1WxIi70UscSU07OLayWvNsJ+5d6lspmyi8s=,tag:hZQm6OQpFoYHesBVD//ICw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
