semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:XPBLRCCmE6oYfGgW3BGQOlNbZULcHLkTmJVe6w==,iv:xMuhDRDdIbZNjmzQA2Txc90kgG3UU+lXdGiJxdSNNeA=,tag:BG5ZbVbBrsUU9fTKZy6tmw==,type:str]
sops:
    age:
        - recipient: age13ycsdrpwydpw89ae5tpmmwzwplgs2ne20k9ypyvknpz6faya7evquq4nmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxc3J1V2M2T3VyYXhIK1F4
            a0JRU3NpelFEM1J2cjRYa1ZkTUdMSW9PS1Q4CjA0VTRmTW85OHZHaktRZ1hFM1ln
            V0ZnZU1tQUdFay9CQjZKRFFIWEhYa2cKLS0tIGlFenNKZmxNUFpUMEhQb2lFRytC
            NjRYdXlGc2c1RnRDOG5iN3haNnhnKzAKapsWoWLuBPFTa9YQg/qCwwp+Nuanm5L2
            cOjLthyskmpNqkFKbyggdTvf+6CFXokk/1yDDv4H1+ofnmttEbCHWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONWp3bCsycllwc1pVYjk1
            SlAyM1p2ZWdKU0dxbklGMEdhRzd1R0Qxa1M4Cm9KdFlFRkJaSDZvQTVVYjNKMFZN
            R3oxN00wdndDQXhCS3hFcE81Y0RTZXcKLS0tIENBSjRBQmxwbi9aK25uS3U4Vll1
            YkxCTjR2SkZ1R2Vhb09yZWxTaEIwaWcKdW8RqiAV8Rel0BV2NWFsvhoxHYvkIrVt
            +80VAFACP+O9rXw+x7yRwsciRlQnNbaFSxtAe+phFqHpMgOjhN0pZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZHpZTWwrL2RSRnZJcW1z
            UHhLVTNIWjl6RTAxL3FaVnJPeVowYnhET1VVCk9pWVRvZ2hkbWtqWDVST0l6UDZp
            bnc5a3lOc3VVdkFRcWI4Z1pPRkpEbGMKLS0tIG1hNmthZ1htNU9TaXB6c0N4UERB
            NnRtUlJLbnlMVitoVnRRbklSb0VGTlEKtLX6mXkU9j/JL/k8dF3JzEOFRqYdoHER
            fDiuu83gNwIHcfcKINSxyKUPKL8o36Ycct5u3NcmGL4/f8+NNsmBEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRDUzNVV6enFyNldNY2pm
            Q3ZTNlRZMU9WUFFKTUlPbjhxRnd3bUR1V0JVCnhiUkJiMzgzeDRuZEZQdlBqR0pa
            TXc1b1NUUW9La29MdjBPMDI0ZkhUWDAKLS0tIDUxTFA1dzZ0YzA5TkwwUUozZ1hO
            OUJJeWJHTjh0TFpzU2R5TkhqZ0k0K0kKHqwSBG37rhcSEEig3ONdjcKCKI9jwb0x
            QkRkOtJjSIvc/+tpnFlN68+P7SlBRQsu5CrJMvlT7dMzHt7Ozs+3PA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l0smk7ddqsfn0a8drh4fvm2vnrgkc44wrnu275n9k9pde9wcyewszc2vys
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejBoQ3NndmdTZEdtWXdJ
            NFZQSW5kS1l4bGlRUE00WVNVSlhZL0xnbWxNCjhOVGNIcFZ5d3loOVR6RWlDVG9v
            ZXNDSDl2bUgwTTNlMTdrVHo3OVplL0kKLS0tIHV0ZjZ5WitNWWRWV1A5TEIxaW1R
            eEp4a2RxamhaY2hkREtSYjJmQk1NSHcKa+/S0FD8eE9JmX7hiEJq6exDjn4Yu2po
            3cs1YHDJWdzl6xTL59MLFifbGqktKVwrUhsTWtDoPvtGW3jI56UIFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OWNsRDZJbEgyUWp6R2Vv
            YzMwdnZKUnBHNTRRZ1Z4dUpJNW1MZ3A3SW5vCjlEc0dWWTVtTVhPTmxZZTZnWXQr
            RUUxcnZJQi8rQmJDU1k4ZVNCNW1seFEKLS0tIFZrWUxxc0Q4L0ZJKzljTjdUeXZp
            WHB5RVlUcUEvUXd2M3crVDFwUnJ5RWsKCiqsJM6++MaDHmhfMXfrC0aPEFOeQZnH
            OjtFu1V97J9hhOr/lsOwbG7xiecGkih1MFKCzkYxShN4OqYLQun6ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T04:10:02Z"
    mac: ENC[AES256_GCM,data:dd/yJdj4EyBawvIWcln2Lz3nMffJxSK1Bp8t9+Mzg8grS9GhASChL7W3m8603F0qCcmAZmsgyC5V6xwtAcmiaCdW+0vrfsj7XkTs/fZcfLVxvWgeSBIkYD0Ajf0DHSJM/BBczAvi2MCJjM6Co0BO2niDFuP5eZHgErqOr+C3p/s=,iv:JGnOgxWchwrQQD0uD2XXfgfoaAbF3blp3LiPlKdnYBs=,tag:cqYczpZzTgMsmSXg1zZmgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
