semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:yAjQzf7IlJ0I80CTBdKaplM6jNaDThUaxMWhAA==,iv:y3oRRhPHtibrtq5NpNQIawAqHs6CacxEtq5yHry4Cy0=,tag:3vrpuaMaoGSBFKaWeLHyeg==,type:str]
bookstack-keyfile: ENC[AES256_GCM,data:BkK7jrmgIy7OUmrErrhqLHecJk13gTMTuzNvwNXcjJaQxzDbz0Stz6LRc6mCgzIgiWbz,iv:AMuco6K5/v9hP6yzWFS43GtMx3giGod7sQ/LF1bgdSs=,tag:239EuedaBBP0we96TWW64w==,type:str]
netbox-key-file: ENC[AES256_GCM,data:vSR05kPuaf788PTHxiTnwP4BQSPxKpunBh7wbaVie93ehxVFdOmpGCGRE1nf3A5Tj44Xxmqx2dkAybgu4ky2nbEmbrdmTC6tqdntAxsiKoJYlKJ5jBfcfiOSEXRt0SDCBf8Ejw==,iv:4qKKwhaslH3216WX/68mM/UefLVRXAvpiH1Jj1TlGSU=,tag:t8e5qigrTxRbDMLihvFcpg==,type:str]
lldap-admin-password: ENC[AES256_GCM,data:Xf9F5DqAXzw6q5pwjEq6ge5GFw==,iv:Qb0dXTZLiwMVrfnFuqjJ4mIfgKycJ6XiIcJB7TZx63s=,tag:801t11KeEIVr21X5JpZE4g==,type:str]
snipe-keyfile: ENC[AES256_GCM,data:9lnP4J6fN4LBSqAHszUd2UJSJvqXbSboPvU/I+usMd65ma7n4+VmJCjisgI=,iv:f1sk5fZCyQN3TgVxhc06fO7G65Q4EFMOkJcjvrtsW6Q=,tag:XxWxFdMikxquHqVTRgtwFA==,type:str]
neo4j-auth: ENC[AES256_GCM,data:uTRkO5njVfmQ2w8FcHqEqcHZjpR3uCcnoDHqMG0TMng0aXM=,iv:7SP0id+8ylPP6Xf91QPHLsjHdRqZId+VNQe0oEK5jvU=,tag:E2hGoZXYFiEzcOQQWwM67Q==,type:str]
bhe-neo4j-connection: ENC[AES256_GCM,data:Vd8S0f/C0DnmEeSQaT6Jjb8WN3d3ClDwcvt/Zzpj60ZXz2eG9Yic2KftRdlo/HteY61BZayR4UUnP6V7Pjht0OM=,iv:Drzz69UeOAhLweJs9ilUJu+x//Z3FgOQtYDlPMc1PR0=,tag:ZTTHVrKGLxu25nhasam6/w==,type:str]
bhe-database-secret: ENC[AES256_GCM,data:AG1YIj84/K/nuvle/s6YJhlfaCrIagQ6Pj+5bQgYNjCzBAvuvAURAA==,iv:QV7+w3HC8PU0v0tOcVbqW62WgLOh70KbvMt5OVdO8y8=,tag:jTYSBEjMlmDkUV1+2PbxJg==,type:str]
kube-token: ENC[AES256_GCM,data:dWbd3z6Ugm7Mf505xNLSXgvn73wPdxyU+Tzt1qcnMu5vCmogT2/jUU+19ZYcCYEuWk6zO1ZYyC8p31UevXFiKIAgtEQQ6QFYvC5hNpnZLJy6apPBFuTshpTLN6dhx/Hg1+SpO/x6bd8Gs7qM,iv:gbSo/i5ykcwZ0IS+3zY9Un6VjTRxylzKvoYZKg2sSBk=,tag:h7gSpcCs4smoZJlN6Eu9Gw==,type:str]
mailserver-password-file: ENC[AES256_GCM,data:ZsxIcoOXTpIbXurW10Yw7tOM5vhi9GJSbbFs++szSXOSkRtUzLwM8eUJwz/BJRXLJnqlwGrapnjJBRUF,iv:wY499BXRpZNfBTuP+TqZX6jWltaN2yeBt8lqPQ+3Kog=,tag:QsfS4rbbbyLslIeDaXpG7A==,type:str]
syncthing-admin-password: ENC[AES256_GCM,data:kujl9MXksxSbDcsFkx74p6vGlnYRMnMdXkopNPwqGkmguMxw1pyLPmTFJRifHbOuxGP/49YgS1QCOME0,iv:N9PYpDytQMCpF55jbh/UJGpUZK74bhBDBayqTH1YFVY=,tag:O/j1ifPQ/a4v36lORFNEIg==,type:str]
sops:
    age:
        - recipient: age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TUt1bGdNbktreGRtanpo
            S2krYXNFdFRxZUxhejJrU3JDd1NIcmlXVmkwCmVMeXRUVlBPZjAxdDd4OUdIVnpy
            ekRqOTYzZ1l2TU9xTmZEcUk5bGM5Q1kKLS0tIGs1SlZyL3I0VnhpU3VmNFlFUlUr
            N2RZakZzVVpIQjZCZmpOZUpPckdqZWsK8loxIGKA0SJ3GR3jJRV8HMLIqXA3UeH0
            xGkgMa0xdB2hBgFuhe+YVoYW62UARusK1ZGGSD6pLB3BtlDtek+Ytw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRjRScWdDZmxIUGlLN1U2
            MVlJaG81bHBhajNNeXhxN0xvV05YTTJNOFV3CkNPMDZmZXdiK3pRZXlhcWk4ajNK
            MCtWRllZMFhiN1dqSVRyNHEyZ09kQmMKLS0tIGxaWjl0c0lCRzlWcSt3UldmN2ox
            SzdsN0huK0hSbnA1Qm43QUN3Q2xBUncKSsjWDeIIU9bOJCrZWWaknVU8NrP7a7hW
            P1sYZIXwplJrxGO6LkOkWizl61gTDJLzmlJpDBZcBA5QsQhL3Qo1hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9vwxjsy220jjeauf2kll6fn3mvltzx9rujvr75ea7w696v4qqvsu376j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UXB2bHMxZ0VwU09Kc0oy
            K2Vqc09ESGJOc1Q5Q0cxa0l2dXVCOFFYQVZvCk04bWZHekIxN1IwSjdPU2RiL1c2
            aTAvVmpXU21mSGZVdFhjeExkUWkvOTAKLS0tIDVuWGNXNkpsSEoxd3prVXRTMkVm
            b1hvYlByamNnL1NyRXVXV2hiQWJhZDQKXEkgo1L0qg1tfcE8kMkmH6rliqTZxaqR
            qCcb3Slide6j0E0GpABRGkI6CFMUOB+b/KCGjFCwuWjZWMdkBjHRbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1atakc2r5uxz97r64lap73muc7gdydvqfpczz8dlwh85pqrr7gpss8kr9j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QmZhZzdXTnpmQ3oxUnlC
            aHoxVGZOa0V4T0xQTVpNTkhCYUt0K1JYSjEwCjlsTFpZQ25kQklDRmdzNW82dkM4
            NjU0S1NScVVieUF2NXhNRk5iMzJFNXMKLS0tIG16QUtHQWpuS2V4amlEVnlETGN3
            YzcxUUJLbnYwTEViMW9KdUVMa1pyTEUKoGj0W46DrbBaIBY1gML3vw6c3Yfmlw8n
            7k50H+92ix87dbf5OyKUbwySvTIHLbXEOI+sbKvLp1ziqP3F3rwpmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14cymtuyupa8xt46xy8e35l0qznq6v7wvjzxzha95hmplxcvc8yesu06jr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RzkrL3hmS3Z2bDhVUWdS
            WkFPdGhoWGF1N0gyVkF6bE9XNDhvSEw5OFIwCk81cmlmUWdxV210QlhFd2U1Y1hR
            Ny9DQk5TTkFvTXFQOEFLdEZYTnBPZlkKLS0tIDJFOVcrbWRzMCtXSlF6c1FDL21B
            QkRINjJDN1JWOWV3SG1VNjg2bTRrTUUKPKxBwm5Kw0IIGnZNJs+BPTBAmjjXw/rd
            aCG8JjCZ5laZ9k50/3WJ5i/t+Y/kUlFS0Pn7Wcy4pUeySwmZP5q6ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkx8zl440ur3ju60cgsulvuwnzkqd9wfjjh928dn0c0tkuksppdqmlzgna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWVJyQXR5Mk1MMk5sanFM
            MDdDMzZzNnA1enNoRkNpc0dUZUtLRUVoSGlVCmJJYlVhMHNjNm40KzM5VERBZkpS
            OFVVQlRsL3NJaHZPN28xTDdJZjN0MVUKLS0tIEhadk84eEhwV2FlQ2Z2d2N4Q1dY
            NFlJYnF4ZlE4YTU1MGRMeGdNVnFjMnMKhY50ohuwDaFO99o60Tt1sNlHM+NkDl9P
            w3VBuZVzEfObiuqMg/uh+syGS2kV1uEWo81/dlgA2JdpXcvjq0OBkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiKzVaM2pYR0JsaldaaFU5
            SUNYNEU4dm9WVmpFVjZGWHU4Zm1HeXlnSnl3CmoyaFYvRDQ4TzNNS3lSaHV0UXBW
            QnNCZDdLVUlJZFZVMEdjRHFWVm5hU2sKLS0tIEtaOGRXODBLblhiNXoxdVJDZU5N
            Z0dTdERUYWtNM2NxNDd5cHJRYXpWb1EKB9NQp06bOpJOFMiGYB59aGOnMFJq4PC2
            hWnlX0tROFDmO+VZh2S7vTreixez/6ce0cv5AhwZH9ehPiKAAZr4jA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ag753fcgermh0lvu7p99snh3g9rn2gkejq8qs3h22rgrgedmreyquf0yw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU0E5SVBHdUhVNzdEZ1FJ
            c0ZRTnRPQWw4aGs5cHVIYTFiRDJDN3dDZ0dvCmxOVFNSc3kzS3BVd1lZS1V6emds
            L1BPZnNYYXBZN0pUUXlkR0tjVytjN3cKLS0tIEZpWkZOblJNZUhaSmgwSmlVb0Jt
            MEdMRXFtRDBNVDlZeHpaWThKdkhNQ2MKq63SyL5ARlX57Bp9pxN5XY88UvESVolD
            NJYMAtolxVu9MChtlVH5IgCD/bTrZFpiEauWj1YLVFYUFWIa9yK/TA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age107607wh3eaq4n9pxjgtvpfy0puf9eul8a4lmtt0u4cnc4t2h749qz29tcw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ejliNFZ5NHgwaDBPQlFv
            aTdmZkJLK2JkNGkyN0JxbkJEU08zcDJEMlJZCmZralVpSDVVSGIyMkd0WTVBWmxV
            NXVjSFdQUnJRdXdXd0xYVG5ObFl0VUEKLS0tIEFEQTNudXZROTRtanpjaGkwK1p5
            cW9iYTZWK3pZbWE2Tjl3ZzB6emtRdkkKcJuguKLRj3C6IwoOf6CB42Ni8hvrjGIu
            EIId2gnwZhOPpSDcE8+uRPboMCD3IB+q/NLfB6p1KcmgVa8ArztLZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkzcyetggc8ftex6awe3pyjy82nw5t390qdzjy5edumplz2v7clscky7r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcjQ4Y0tmUU43SFAwYTRL
            ZHhpb3dlSDNhTndvd3d5bXlvNVNmeE83c3hrCnJTbWk4MW5VemRpRjJCaExBdGYy
            SkdWazdQSGJhTC9KQlgwclAyM1h5Q2sKLS0tIFcrdUxlZVlzajYzUEJ4NHlRK0Z2
            T3BUdEQvTzAzTCtRaW1MbmplVGxPN00K+KsR/vpiGIFruEZLuw24cnrlN0yjV5+K
            ucw6V5UwU3GQShaiuktYqUEl7qN5nrV9L/tTUPFED+LXzIugX5pPEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMExxUVMvTWJMYzhUbkJ5
            L25hR3lON0FyRHZPbXVqbElGNStBalpuSENRCkVkYnY5UzlpMU5DZHUxMS8wWWtN
            L1dic0tFUXRGb3cvajBBK091QWRZYm8KLS0tIGVzL296eHVIa1pHY0JzTUpWNERz
            b09IRHdGeFNadCs1UG15WTVnaWFrSHcK5VQh1vxrPPKzZq17ubeVwOlw04DBEtp5
            i/mBO8/MoQfl0WlJfIMjYrfivY+A7vwu0j9jM8J4Xy/dOrEdHnp5Uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb3J2YkJnMk9RaWRvL05R
            RzA3YzBrM0FwMk9jNWQvZTRYejNwQXNuZ0dBCmVXcVVUZ1NHK2ZUd2RnSmtaVGNa
            TWlpNUtIaFR1eEdDbktWK3lCYjVESkkKLS0tIDhlNmVFRmI4dkRCOEJaMStPaFBG
            bTIwWW4zYnYrOU5CVTJTVTZvcTBYaFkKyEYOBE072y5P4gHJxKN3U85XqaNm0THB
            oYJ1+fJuUUTobNvZZUPCtGotYq/nJtNi0UQlSZO2SWfYSdwv+n8G4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T05:30:54Z"
    mac: ENC[AES256_GCM,data:hEdZf0ObxzD6wYng+fvK45rPu2jfBt4VIZk4SE3Kt+9MNBMgCgQtUaSNbdt0i9N8ZREymomu726/SRKK/ML/bIGmZJ9Akio5VT/RHsutpvMVhVw0fiV/6fCcOFs33ugIRbhby+1MOwcykYK0A1zMPIXjXuzgeaoOfUn08XI+V8k=,iv:rK6hDirBU3AUw8Uybnb574XUY5O+f6q+9adPrIlbEXg=,tag:K/HpcwwnJlteNKEphvVhAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
