semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:yAjQzf7IlJ0I80CTBdKaplM6jNaDThUaxMWhAA==,iv:y3oRRhPHtibrtq5NpNQIawAqHs6CacxEtq5yHry4Cy0=,tag:3vrpuaMaoGSBFKaWeLHyeg==,type:str]
bookstack-keyfile: ENC[AES256_GCM,data:BkK7jrmgIy7OUmrErrhqLHecJk13gTMTuzNvwNXcjJaQxzDbz0Stz6LRc6mCgzIgiWbz,iv:AMuco6K5/v9hP6yzWFS43GtMx3giGod7sQ/LF1bgdSs=,tag:239EuedaBBP0we96TWW64w==,type:str]
netbox-key-file: ENC[AES256_GCM,data:vSR05kPuaf788PTHxiTnwP4BQSPxKpunBh7wbaVie93ehxVFdOmpGCGRE1nf3A5Tj44Xxmqx2dkAybgu4ky2nbEmbrdmTC6tqdntAxsiKoJYlKJ5jBfcfiOSEXRt0SDCBf8Ejw==,iv:4qKKwhaslH3216WX/68mM/UefLVRXAvpiH1Jj1TlGSU=,tag:t8e5qigrTxRbDMLihvFcpg==,type:str]
lldap-admin-password: ENC[AES256_GCM,data:Xf9F5DqAXzw6q5pwjEq6ge5GFw==,iv:Qb0dXTZLiwMVrfnFuqjJ4mIfgKycJ6XiIcJB7TZx63s=,tag:801t11KeEIVr21X5JpZE4g==,type:str]
snipe-keyfile: ENC[AES256_GCM,data:9lnP4J6fN4LBSqAHszUd2UJSJvqXbSboPvU/I+usMd65ma7n4+VmJCjisgI=,iv:f1sk5fZCyQN3TgVxhc06fO7G65Q4EFMOkJcjvrtsW6Q=,tag:XxWxFdMikxquHqVTRgtwFA==,type:str]
neo4j-auth: ENC[AES256_GCM,data:uTRkO5njVfmQ2w8FcHqEqcHZjpR3uCcnoDHqMG0TMng0aXM=,iv:7SP0id+8ylPP6Xf91QPHLsjHdRqZId+VNQe0oEK5jvU=,tag:E2hGoZXYFiEzcOQQWwM67Q==,type:str]
bhe-neo4j-connection: ENC[AES256_GCM,data:Vd8S0f/C0DnmEeSQaT6Jjb8WN3d3ClDwcvt/Zzpj60ZXz2eG9Yic2KftRdlo/HteY61BZayR4UUnP6V7Pjht0OM=,iv:Drzz69UeOAhLweJs9ilUJu+x//Z3FgOQtYDlPMc1PR0=,tag:ZTTHVrKGLxu25nhasam6/w==,type:str]
bhe-database-secret: ENC[AES256_GCM,data:AG1YIj84/K/nuvle/s6YJhlfaCrIagQ6Pj+5bQgYNjCzBAvuvAURAA==,iv:QV7+w3HC8PU0v0tOcVbqW62WgLOh70KbvMt5OVdO8y8=,tag:jTYSBEjMlmDkUV1+2PbxJg==,type:str]
kube-token: ENC[AES256_GCM,data:dWbd3z6Ugm7Mf505xNLSXgvn73wPdxyU+Tzt1qcnMu5vCmogT2/jUU+19ZYcCYEuWk6zO1ZYyC8p31UevXFiKIAgtEQQ6QFYvC5hNpnZLJy6apPBFuTshpTLN6dhx/Hg1+SpO/x6bd8Gs7qM,iv:gbSo/i5ykcwZ0IS+3zY9Un6VjTRxylzKvoYZKg2sSBk=,tag:h7gSpcCs4smoZJlN6Eu9Gw==,type:str]
mailserver-password-file: ENC[AES256_GCM,data:ZsxIcoOXTpIbXurW10Yw7tOM5vhi9GJSbbFs++szSXOSkRtUzLwM8eUJwz/BJRXLJnqlwGrapnjJBRUF,iv:wY499BXRpZNfBTuP+TqZX6jWltaN2yeBt8lqPQ+3Kog=,tag:QsfS4rbbbyLslIeDaXpG7A==,type:str]
syncthing-admin-password: ENC[AES256_GCM,data:RrvMyJRxbWa/M4jn60e73vcccEoRvnB4Ww==,iv:R7Q5aml4hbR3EwN2fAsJ+i6LcTqY7T3xPfjZYSA5KUU=,tag:hPxnccF+xsdrE0lmcJzl0Q==,type:str]
sops:
    age:
        - recipient: age135l98d5fxzlt43xw8ljmgqa6st7j00mzw9d3r7uq2lyvxxrrtd7q856mss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVG03L0twZnFjYjJ5SGF5
            bjM4WU8xMG12TVBKYzNyM2l0UVVpSk5uOENVClN0c1ozTEVDSEwrOFJCdFA1dVV2
            TmZiMm5tNmdSVCt0a2lVQlRkemNRdFkKLS0tIDVYLzl1bDN3SVBvT0xrb2huOW5Y
            SERwMHJXck9oaXh6dlZNdEhVeHY4bTAKtf4Hlx5/l7tQdG6srIRj96wxHLhOapJM
            gr4XllQx1KsSSk0MZ5XuN/kH27UuJTGpP6PFL/09GY/0VV8nDjtJ6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNXVlcVZyY1NCcDh6Yy9r
            SVc5NUpMTVU1VEV6dnpXR1B4UVJCcjUzbkFZCm5JWWdjWFFvY0FCZjJOS0k3VlF0
            TVdMb3AyVGE1My9QV0JiL0xFbmVqWHcKLS0tIGZCVlJEL2RMU1BHRVpUUFcxNGxs
            RWVnTmZyVVcxOFpsZldPNzdnenBVNDQKuxF7fzLh0nObBb+GLJByvNRZBl89/eYz
            PhmNWtOCNx3rZ8UDJwNe17UhsbcYjcHyvIwl8DZ/tIfZY2NIzQ4nlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN3lpYWZvbnpOTFlTSlVu
            Tmlwb3hkMTgvZDZjVkxPaHNySE5LbVRiVGl3Ck1hNXBPN3I1bmEvVURxeUF0ZnF2
            Mi9vNzIxWWdlVnh5NUJMNnh3K0YwTG8KLS0tIFdNcW93NFo3QnZBTjV0a0k1aUxI
            TmFlOUpqdXlXcmNQclhyVmZDL0hCb1kKXkWzqHfOMNVRmlIXSOaJVgd6tjwSvDbO
            AnxzzhA1P+tlN9ZGXwN3rb3s9lFvfZK+xCFJ9QfCZ/T1yAnh4rck/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9vwxjsy220jjeauf2kll6fn3mvltzx9rujvr75ea7w696v4qqvsu376j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbzRMNzJYNnVtRHZTYjFL
            dDUrVEQwa2dqazh2NGRRbDdrMThNZTk4YVRnCkdCNXVQSHJoc1NkWmh6M0tkNVQ4
            NmtmNnlkdjd0QW9iR0NjTFIzS3duWnMKLS0tIGFXdHhPVEhicTVvaXdtM2NYMDlo
            WDNuVTlFL1NnNCs2VGlDczhiYnJ5NGMKgk83j9UOuMt09Cvj37x7AJ0ViDXZX6en
            M2gjy4WTOF+5FTQBRmJPEdbFCFawVJ1hC/06JGGa0JJSe+oTmq5K0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1atakc2r5uxz97r64lap73muc7gdydvqfpczz8dlwh85pqrr7gpss8kr9j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTWxZNStkOXFsRlhWaVdp
            eTRIVmFpQzk1dDFmTVN3Q0xmalRsaWJ4OFdRCkxUclhPcEsxWHJzcWpGNUZHdmxL
            NUNZVEFsemljempsV3U2UkhoNHdHdmMKLS0tIGxNQmNiWUFscFpMaHZQTFAzcTFS
            aktacWk1cnN6RXdsR1R6MUJvWDY2MW8KCJTTT8dE9CblXR/pc3tUaRrj1zB0vdys
            ew6VUR4FO38T44E++aJA5xnufim/qahJg7mmepvFjlXd9BP41X8gLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14cymtuyupa8xt46xy8e35l0qznq6v7wvjzxzha95hmplxcvc8yesu06jr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bEZvcGZnZTUwUWJKMFlL
            d25kZzJqdVJQcWZVOEhrQVRXMSt5Y3AzbTJrCnpNTTZyeVZlN0RvUVlWNFdpVk1Y
            YmFUbjIvdWptSExsNDdzZVM4cGlMclUKLS0tIEI2bmRBa1o5MHp1OWRsVXc5ZFhw
            eXhXdkRRdmpvNWQxKzd1cUZlSlRIVkEKly+p4cqASdFqpJ57QazuUqX6Emg3oqLU
            B0qYAcVa5NvOj6+ovCRzzm35udvoxT89/aSC0j0L7LR5q4IjjSDRUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkx8zl440ur3ju60cgsulvuwnzkqd9wfjjh928dn0c0tkuksppdqmlzgna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL29aTWN3NjVlcHB2dkV4
            TkdGcldKT3N2aGlvZThraDhwTGt6ekhqZlRRCjA2dHA0QzhMVWRGMHNza09FOTVx
            SmoySTZsTEhuNG9XRGFTc3VjKzMyZkkKLS0tIEx4bWd6Njc4YVdEczJXMTRaTHkw
            M0g1QWZlZTNjMXl2OG50b2tXQXpIMkEK4OUlgagfqdtwyuuL4w4bpkT4QoomDe8N
            w94w8Upjl1NbsFnIZO9dkvBTor7j7fP/lfSkP1ECXb5l9DjPe897Xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc3ppbXlDcVpwSHpzM3Fo
            RHVCWGE1YlhGNmt0MmYwbjBHQW1GVDhISWxzCjZmcnRyLzVjNDVpVVFTSW9zRW9n
            Zi9OSElyMUdtTHBPczhjRzN2cGFDV3MKLS0tIGlKL2Q2Y2c5SXVWRGJSYjZrSVdm
            MndDRkFNSVZlb29raGRmOEVmNmV5a3cKZZjbvO+rDiG4l+UJ0xiXPTeVxFk0sytg
            j8hfTcndIqrDQc1yyl5WSYaFlUZQYQKYF4913viM7F+1xGaqAi1H1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ag753fcgermh0lvu7p99snh3g9rn2gkejq8qs3h22rgrgedmreyquf0yw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZzhzanlaWWxJTFJNOUdm
            VmEzRGJyZ1RraWV6R21mdHpNVzZoYVVmMEdBClZETXlLSGhqYmk5bzgvQXMxN09r
            LzlicDJtY2ZBOUhqSnNwUTVzbXRUWEUKLS0tIG5sVDE1eFJzSWliYkZST3FITmJm
            R0VXMG1qczJYNklSUXV6bkFjMmtMdXcKO1GAjeoTV1lsilqjhwk14ZA+XRKoVvJ8
            +mJQf+6H62N3X3lZIUcKonl+EoZDI6P6fdzUzVKvvNbFKTfjyrLIDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age107607wh3eaq4n9pxjgtvpfy0puf9eul8a4lmtt0u4cnc4t2h749qz29tcw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbEowdFRUMlRYdlFmdVZw
            MVBQTW9pNFFRSTlZMlFuNmoyT1MvdWpVWjJrClJRRk1HbmZXNWtzdEN6dEdja2RG
            KzNsNU1xYTFqU0RMSm1YajZwTnUreWcKLS0tIHpFZEVESjY5K00xZTEzOVc5M1U5
            SVZVQU9QZjNYbWlSc2pCQlpiNXlLUTQKGtsPbCL1ESi7joQjEUWZgVpS2UD79b5i
            2FoShi9gzC8QifWr350C+EWXKYQ+0uV887hGSoqhh3v5FSA2I9S1GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkzcyetggc8ftex6awe3pyjy82nw5t390qdzjy5edumplz2v7clscky7r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaEtRSy91V1l4MG10UjVa
            cm01UTJPeUQ4UmdWWDVIVVVmdkJsUG5SOVZFCkxkcld4cjlSMXNJd21RcEFJQlpK
            Q2pVMWtxZUdjSG5BcXZzSHg2Rm1wZEEKLS0tIHJEcVlYU0FFOVo2YmFoNDh4bVVp
            am9NMFJ5MmJQOU4wM1pXRStiazE5aDAKS7VqkUgPabAWsWvEzyBvBFlu2EoZeYC9
            GSF97xvDdaspZvtgAP0hPjmc2PGg8j1uazItcZDkgjth/urn25UpzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGN5THlDK3FFN2c5SVNN
            dy91bXRyTml3bVJpaFZpZ0ZNK3Judk9jbGhNClhVODRCeVZHVG5uZUpZOWtzZC9J
            SDVVRmZQV0JuQlJWeEVFTDZJc2YwQzQKLS0tIGFwZ3phZXdOZHZpZVNybXQ0STdn
            RW1SL0NPam9SUTVSRC8reXRQa3hPZVEKdVH4lGC9I6LbAidx4wK0UIA2CwDl5w5w
            c7SMC7DpC6l8eN0wIuH3MoQZ17ZbPmxaA607ZzFGkhTHeDlAohZfHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSmVLa0lYVThPTFFxV2tz
            a21uY0Z0RmtSRWdMdE5oQ29tTlFUcXFPdDJjCmVweTE1NmgzQ3FJbE02dUdYSDFS
            YW9pQlJwaDJEWjNiWDRRWXorZWpmR00KLS0tIFBGS0JvS0NNMmJPY1FhQnVEUFpJ
            SE00N2V3WGJudGZkMEowVUZ6NE5rQ0kKtf0DOT22E2H7avH3lrlQViX2q6sNWFCc
            NN/SzspkS3P2cnCM8ZE5ioFXE3n9e7jytzBe26GKiCZK/XZXTZbpkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T07:39:45Z"
    mac: ENC[AES256_GCM,data:3X3PccMVc0QO7NN2nX14bvwnjdO+AC28Iz9lD0snKWTkMyXa2eTVj0dLq4x4xnh3IamRX+Bar74YuO9Sf9T4NNlfw2etZ7JPRbKSX3Chk38xrCtBgV1YjcoVNGBkKZIvEpuTDjRPZApJcUwCguct6+NwT4vwxnTMv/fIpWpyifw=,iv:CA5W2aiJAwpIFtJBz5DzHp00yx3TCTJfFsZJyDQlan8=,tag:z88GcW5rdqWpxA6uDPDlUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
