semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
vault-root-token: ENC[AES256_GCM,data:yAjQzf7IlJ0I80CTBdKaplM6jNaDThUaxMWhAA==,iv:y3oRRhPHtibrtq5NpNQIawAqHs6CacxEtq5yHry4Cy0=,tag:3vrpuaMaoGSBFKaWeLHyeg==,type:str]
bookstack-keyfile: ENC[AES256_GCM,data:BkK7jrmgIy7OUmrErrhqLHecJk13gTMTuzNvwNXcjJaQxzDbz0Stz6LRc6mCgzIgiWbz,iv:AMuco6K5/v9hP6yzWFS43GtMx3giGod7sQ/LF1bgdSs=,tag:239EuedaBBP0we96TWW64w==,type:str]
netbox-key-file: ENC[AES256_GCM,data:vSR05kPuaf788PTHxiTnwP4BQSPxKpunBh7wbaVie93ehxVFdOmpGCGRE1nf3A5Tj44Xxmqx2dkAybgu4ky2nbEmbrdmTC6tqdntAxsiKoJYlKJ5jBfcfiOSEXRt0SDCBf8Ejw==,iv:4qKKwhaslH3216WX/68mM/UefLVRXAvpiH1Jj1TlGSU=,tag:t8e5qigrTxRbDMLihvFcpg==,type:str]
sops:
    age:
        - recipient: age1p0ccch342uttsucya2kvgqqrf0rmqy3vvnq38tthw9l424lyffjs0vytjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUblJSbFRiQ1NHeFFYdW12
            bzZOSGxlbVErM2MrbGVjeVQza2VsZ0sxL0U0CjBqV2Rxb2VFRFd2OXp0UCtiQzRh
            dWUrLytlMFZBWHRVVmlZT0pldDJUQTgKLS0tIHJKK1UxdlVsZDBoSFBuQ2NJNytr
            YTRWQVpCblpsZVl4L2NCN1cwVHRjWjAKlK9ri3lEsmZcqO/POgFBnqcnDNpyElZu
            Pw/Jk+fSeqwrUFOpT5kOVjTGenirnsz0AvRdt8dx2Mx08CoHvOkYzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZHB5T21GZmo4eVB2TGxP
            ckRGOW1nY05pdEo1S0pXNURJUzN0TjVFNUhrCnk5WCtJQTV5d3UvYlZsRFJmN3Vm
            QjdMMElQaTMwdFhBdnNiU0JhQTZFamMKLS0tIDJOUmRxdlpHZmhKY28rU1I5Y0xv
            aVpNa0F1WlJZQVBOWFZlTmRTZDhvQlkKMLRvtIm9aF68w+M/PeSp6l8NZgqMXcTG
            DGKjo23gyyG6oyQ67LBCFmBjMDwFN5XJth8ruDXdZPP8I4yBSYuqmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ycsdrpwydpw89ae5tpmmwzwplgs2ne20k9ypyvknpz6faya7evquq4nmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YjN0M0tDUjUyS3Zrcy9y
            L2VVdDArSStQN3VCVVByQklOMUZVdGNwd2lrCkpOWk1wU0xUNmdwS0ZSY0tMWVUv
            dXFEWDJhZ3hoeC9KTm9vdFVJN2c2ck0KLS0tIDl1aHhTTk1nQ3J4NVdZV0RxdSs4
            SkJqYmtoNDJCMlllTSt6QTNzZVhIbHMKptFyVGuAvT02sz97Wt5gLgP+MbDk4/tx
            KZMtrmH3aL9NYPUtD007NPvF6PQgcRmLyLhAzZD+o06VCsyJQohxDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5R3JkRXZOMWNNd2Z0YXVJ
            V3BIaWx1VU9Nb3R5TVowc0J4UjljZktMd0ZZCndjLzhkZU1LUU1DWjFLSWJjNDBO
            YVBNRStpL2I1WlhseERVRnZjOXhjRTAKLS0tIG42Z3pMVlhON3BEVUxWVHFwaC9q
            YUhGdFVBdThlaHg0T3RxOVR3YWl0YjgKfxMu/pTloP3mqF5Wobh0sa8wD4ids/QR
            pgeSb4ysS0f7LvpYBtI9VG+yTtpg8TwVafoYczGd4zpIygcCebgzDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age107607wh3eaq4n9pxjgtvpfy0puf9eul8a4lmtt0u4cnc4t2h749qz29tcw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUHhrTzlRUnBWSnQzeXkz
            dWFPYk92VDlWdFFHVE1SdE9pN3JMWmhiOGtRCmg2QXpaOWcwZmV1QVdkQ0VIcTgy
            ZHhXSFozQ2t2eTZtT0lGN2Rxd0xqakUKLS0tIDUyc0xpYnJCQzZacmE5T3VVc0Uz
            YzBuaUplcmowRmtTWG41YzR4S3ozTDgKAHY2XBRmifMeIoUzmBQ9K4t7/jib/40u
            ZPJ/W7zoK33bddZg+97I32WgKlDx7J/0X2TbxLdl6SJz6oRdA+MuYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkzcyetggc8ftex6awe3pyjy82nw5t390qdzjy5edumplz2v7clscky7r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTW5neUpEN2UyNFh2ZlpP
            LzdPMVdyblZPSWZJdHNJM3FwanNnMnl6Z1hjCklFQ1FmSjcrajZrbHRnMVRNMDRl
            dWR5V0xoZDBzaGlLeFhUSjhnUVpaZXMKLS0tIE53a1REbHl4MzFCQVUxTzdQRzVw
            b1JWaTBwWWs1bFZsT0Q4d1VQVmNGcUEK8FUBd6B+/aTEawNC6bTgtiuq4ifTml4S
            hzSeGzuAXSdW+B3O6AUp1prYFo/gTgl3/akDX7DONlUwJJ6n/OHV8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157pg04an45lhvwln3tdc2gc9hljt740cvehdl006v3jz9d0s2vaqteq9y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZURJUW5XL2twazNpdTE0
            MGRRZTRQMm1lWE95R2lXa25mZm95Rk5Jc0RnCnBzdEVJc3pzVU85Ym1ZRkVUeEVo
            cFRHMXNKeDQ2eWxucGNUcXova0crT00KLS0tIEMwOTJjNm92dlBrTXVkSVozdEpk
            c0dnV29rL2xsMlRNaHJOZ2hlOStTRFUKMuAiS2LIgU/3NlZcZJM9J6TlD8rykfZL
            g9JpBC+E1hI2KbLxxZfcgB0mvbq6JkpgaPZcnBbLi/n8A84+ZPL2ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdVJnWTdBMklXSVd0THVU
            NVdNSnBDTWtqSmhMWVFsS1ByekxrT0h4ZXhzClI3MWZiNnkvd1R2L21RQlJNN0JV
            NDJ0Sy84OHE3U1hiK3paR2Q5bzFiNGsKLS0tIGMvWTNUSzZhK1ozVklJa0ZQNFFz
            dzBQd2RIRFRJUnBnNlVUcW95SHBRUVkKa1l/3PabIgqwITSpRWbfd7kcEQJI1qtu
            29Z1x50Q+vJJo3808n5ygDTsTxQ8EPm05rg70w89w0q+FLYtiHLZvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T04:45:58Z"
    mac: ENC[AES256_GCM,data:7gS5l1b9+u4219x+1Km0lgWt2nCQzgAXKi39GVGXBtAVTkwlIYSpAgqkyZPbpyaz7HY9lAyGmZK6MO+ciRm1Jmdba2PlSXQpNKn7HH/N31hs0XUbd6AOkhlYMIoDl7fzqZjFYMMAYHefgE7xtbY33JuiHvtzitwDfZ16ssIwmGI=,iv:p8AP6scAC964lwKFZcMBF8J4EMp1fYXnDrzQ/vOa7UA=,tag:1uW+cZWDZMnRYnW3Nch8qg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
